# Generated by Django 3.2.5 on 2021-07-22 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter menu item name', max_length=30, verbose_name='menu item name')),
                ('discount', models.IntegerField(blank=True, default=0, help_text='enter item discount', null=True, verbose_name='item discount')),
                ('price', models.FloatField(help_text='enter item price', verbose_name='item price')),
                ('image', models.FileField(blank=True, help_text='upload image of item', null=True, upload_to='cafe5/menu_items/images/', verbose_name='item image')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, help_text='date of creation of item', verbose_name='date of adding item')),
                ('modify_timestamp', models.DateTimeField(auto_now=True, help_text='date of modify of item', verbose_name='date of update item')),
                ('category', models.ForeignKey(help_text='define category', on_delete=django.db.models.deletion.CASCADE, to='cafe.category', verbose_name='menu item category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=50)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('menu_item_number', models.IntegerField(default=1)),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cafe.menuitems')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=3)),
                ('cafe_space_position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('final_price', models.FloatField()),
                ('time_stamp', models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 22, 18, 33, 7, 356393))),
                ('orders_id', models.ManyToManyField(to='cafe.Orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='cafe.table'),
        ),
    ]
